job:
  name: ${job_name}
run:
  dir: ${base_path}/${project_name}/${hydra.job.name}/${attempt_id}
sweep:
  dir: ${hydra.job.name}
  subdir: ${hydra.job.num}

job_logging:
  version: 1
  disable_existing_loggers: false
  root:
    handlers: []

callbacks:
  git_infos:
    _target_: accelerator.utilities.hydra_utils.callbacks.GitInfo
    clean: false

  env_setter:
    _target_: accelerator.utilities.hydra_utils.callbacks.SetEnvironment
    enabled: true
    env:
      PROJECT_NAME: ${project_name}
      JOB_NAME: ${job_name}
      ACCELERATOR_DEBUG: true
      MLFLOW_TRACKING_URI: sqlite:///experiments/${project_name}.db

  set_log_file:
    _target_: accelerator.utilities.hydra_utils.callbacks.SetLogFile

  setup_mlflow_db:
    _target_: accelerator.utilities.hydra_utils.callbacks.SetupMLFLOW
    enabled: true
