data_dir: ~ # dataset directory
base_dir: ${base_path}
experiment_dir: ${hydra:runtime.output_dir} # experiment directory
log_dir: ${paths.experiment_dir}/logs # directory with logs
base_artifacts_dir: ${paths.experiment_dir}/artifacts # directory for artifacts
base_checkpoint_dir: ${paths.base_artifacts_dir}/checkpoints # directory for checkpoints
checkpoint_path: ~ # checkpoint folder

json_path: ~
dopt_path: ~ # paths
